pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = 'us-east-1'
    }

    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Choose Terraform action to perform')
    }

    stages {
        stage('Checkout SCM') {
            steps {
                script {
                    checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/haleem00/terraform-jenkins-eks-mycode.git']])
                }
            }
        }
        stage('Terraform Init') {
            steps {
                script {
                    dir('eks') {
                        sh 'terraform init'
                    }
                }
            }
        }
        stage('Terraform Validate') {
            steps {
                script {
                    dir('eks') {
                        sh 'terraform validate'
                    }
                }
            }
        }
        stage('Terraform Plan') {
            steps {
                script {
                    dir('eks') {
                        sh 'terraform plan'
                    }
                    input(message: 'Are you sure you want to proceed?', ok: 'Yes')
                }
            }
        }
        stage('Terraform Apply or Destroy') {
            steps {
                script {
                    dir('eks') {
                        sh "terraform $action -auto-approve"
                    }
                }
            }
        }
        stage('apply the kubernetes app') {
            steps {
                script {
                    dir('Kubernetes') {
                        sh "aws eks update-kubeconfig --name my-cluster-terraform"
                        sh "kubectl apply -f /Kubernetes/"
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
